name: sleep-disorder-pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.12

  # Data processing & ML
  - numpy>=1.23
  - pandas>=1.5
  - scikit-learn>=1.2
  - joblib

  # Tracking & serving
  - mlflow>=2.4

  # Visualization
  - matplotlib>=3.6
  - seaborn>=0.12
