name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MODEL_NAME: "cc"

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow joblib matplotlib seaborn

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Debug list mlruns
        run: |
          cd MLProject
          echo "Cek isi MLProject:"
          ls -lh
          echo "Cek isi mlruns:"
          ls -lh mlruns
          echo "Cek isi mlruns/0:"
          ls -lh mlruns/0 || true

      - name: Get latest MLflow run_id
        run: |
          cd MLProject
          echo "ISI mlruns/0:"
          ls -lh mlruns/0
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "RUN_ID = $RUN_ID"
          echo "Cek isi model:"
          ls -lh mlruns/0/$RUN_ID/model || true
          cat mlruns/0/$RUN_ID/model/MLmodel || true

      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "${{ env.MODEL_NAME }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.MODEL_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.MODEL_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.MODEL_NAME }}:latest
