name: Sleep Disorder CI

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci.yml'

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow joblib matplotlib seaborn

      - name: Run MLflow Project
        run: | 
          cd MLProject
          mlflow run .
