name: CI/CD MLflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'mlruns/**'
      - '.gitattributes'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT 
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          lfs: true

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "Workflow path: $GITHUB_WORKSPACE"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn joblib

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | cut -d'/' -f4)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Track mlruns/ with Git LFS
        run: |
          git lfs track "MLProject/mlruns/**"
          git add .gitattributes
          git commit -m "Track mlruns folder" || true

      - name: Set git identity
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Add & Commit mlruns
        run: |
          git add -f MLProject/mlruns/
          git commit -m "Add mlruns artifacts from CI" || true

      - name: Push mlruns to repo
        run: |
          git push origin main

      # === UPGRADE: Build & Push Docker Model ke Docker Hub ===

      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "sleepdisorder_model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag sleepdisorder_model ${{ secrets.DOCKER_HUB_USERNAME }}/sleepdisorder_model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sleepdisorder_model:latest
