# .github/workflows/ci.yml
name: CI/CD MLflow Sleep-Disorder Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'MLProject/mlruns/**'
      - '.gitattributes'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          lfs: true

      - name: Setup Conda and create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.12.7'
          environment-file: 'MLProject/conda.yaml'
          activate-environment: 'sleep-disorder-pipeline'
          auto-activate-base: false

      - name: Verify Conda environment
        run: |
          conda info --envs
          python --version

      - name: Run MLflow Project
        run: |
          cd MLProject
          conda run -n sleep-disorder-pipeline mlflow run . --env-manager=conda --entry-point main

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs -y
          git lfs install

      - name: Track mlruns directory
        run: |
          git lfs track 'MLProject/mlruns/**'
          git add .gitattributes || true
          git commit -m 'chore: track mlruns with Git LFS' || true

      - name: Commit mlruns artifacts
        run: |
          git add -f MLProject/mlruns/
          git config --global user.name '${{ secrets.GIT_NAME }}'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git commit -m 'ci: add mlruns artifacts' || true
          git push origin main

      - name: Build Docker image from MLflow model
        run: |
          MODEL_DIR="$(ls MLProject/mlruns/0/models | grep m- | sort | tail -n1)"
          MODEL_URI="MLProject/mlruns/0/models/${MODEL_DIR}/artifacts"
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest"
          conda run -n sleep-disorder-pipeline mlflow models build-docker -m $MODEL_URI -n mlflow-model
          docker tag mlflow-model $IMAGE_NAME

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest"
          docker push $IMAGE_NAME
