name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATASET: "MLProject/namadataset_preprocessing/Sleep_health_and_lifestyle_dataset_preprocessed.csv"
  MODEL_NAME: "cc"

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow joblib matplotlib seaborn

      # Run MLflow Project (dengan env-manager=local)
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      # Ambil run_id terbaru dari mlruns (pastikan mlruns/0 sudah ada)
      - name: Get latest MLflow run_id
        run: |
          cd MLProject
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Build Docker Image (menggunakan model terbaru)
      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "${{ env.MODEL_NAME }}"

      # Login ke Docker Hub (pakai secrets di repo, wajib diset di GitHub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag ${{ env.MODEL_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.MODEL_NAME }}:latest

      # Push Docker Image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.MODEL_NAME }}:latest
