name: CI/CD MLflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'mlruns/**'
      - '.gitattributes'
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT 
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          lfs: true

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "Workflow path: $GITHUB_WORKSPACE"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn joblib seaborn matplotlib
      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install
      - name: Track mlruns/ with Git LFS
        run: |
          git lfs track "MLProject/mlruns/**"
          git add .gitattributes
          git commit -m "Track mlruns folder" || true
      - name: Set git identity
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
      - name: Add & Commit mlruns
        run: |
          git add -f MLProject/mlruns/
          git status
          ls -R MLProject/mlruns/
          git commit -m "Add mlruns artifacts from CI" || true
      - name: Push mlruns to repo
        run: |
          git push origin main 

      # Build Docker Image from MLflow model
      - name: Build Docker Image using MLflow
        run: |
          MODEL_URI="MLProject/mlruns/0/models/$(ls MLProject/mlruns/0/models | grep m- | sort | tail -1)/artifacts"
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest
          mlflow models build-docker -m $MODEL_URI -n mlflow-model
          docker tag mlflow-model $IMAGE_NAME

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      # Push to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-model:latest
          docker push $IMAGE_NAME
